const MAILCHIMP_HASH = "md5";
const MAILCHIMP_DIGEST = "hex";
const MAILCHIMP_USER_SUBSCRIBED = "subscribed";
const MAILCHIMP_USER_ACTIVE = "active";
const MAILCHIMP_NEWSLETTER_TAG = "Newsletter";
const MAILCHIMP_SIGNEDUP_TAG = "SignedUp";

module.exports = {
  MAILCHIMP_HASH,
  MAILCHIMP_DIGEST,
  MAILCHIMP_USER_SUBSCRIBED,
  MAILCHIMP_USER_ACTIVE,
  MAILCHIMP_NEWSLETTER_TAG,
  MAILCHIMP_SIGNEDUP_TAG
};
